language: python
python:
  - "3.6"
  - "3.7"
install:
- pip install --upgrade -r requirements.txt
- # make sure tests run with these minimal requirements
- python setup.py develop
- py.test --version
script:
- py.test -v
after_success: coveralls